#pragma once

#include "Common.h"

namespace Puma::Athena
{
	Json AthenaProfile = R"(
	{
		"_id":"",
		"created":"",
		"updated":"",
		"rvn":1,
		"wipeNumber":1,
		"accountId":"",
		"profileId":"athena",
		"version":"puma",
		"items":{
			"puma":{
				"templateId":"CosmeticLocker:cosmeticlocker_athena",
				"attributes":{
					"locker_slots_data":{
						"slots":{
							"Pickaxe":{
								"items":[
									""
								],
								"activeVariants":[
								
								]
							},
							"Dance":{
								"items":[
									"eid:dancemoves",
									null,
									null,
									null,
									null,
									null
								]
							},
							"Glider":{
								"items":[
									null
								]
							},
							"Character":{
								"items":[
									""
								],
								"activeVariants":[
									{
										"variants":[
										
										]
									}
								]
							},
							"Backpack":{
								"items":[
									""
								],
								"activeVariants":[
								
								]
							},
							"ItemWrap":{
								"items":[
									null,
									null,
									null,
									null,
									null,
									null,
									null
								],
								"activeVariants":[
									null,
									null,
									null,
									null,
									null,
									null,
									null
								]
							},
							"LoadingScreen":{
								"items":[
									null
								],
								"activeVariants":[
									null
								]
							},
							"MusicPack":{
								"items":[
									null
								],
								"activeVariants":[
									null
								]
							},
							"SkyDiveContrail":{
								"items":[
									null
								],
								"activeVariants":[
									null
								]
							}
						}
					},
					"use_count":0,
					"banner_icon_template":"DefaultBanner1",
					"locker_name":"",
					"banner_color_template":"DefaultColor1",
					"item_seen":false,
					"favorite":false
				},
				"quantity":1
			}
		},
		"stats":{
			"attributes":{
				"season_match_boost":0,
				"loadouts":[
					"puma"
				],
				"rested_xp_overflow":0,
				"mfa_reward_claimed":true,
				"quest_manager":{
				
				},
				"book_level":0,
				"season_num":0,
				"season_update":0,
				"book_xp":0,
				"permissions":[
				
				],
				"book_purchased":true,
				"lifetime_wins":0,
				"party_assist_quest":"",
				"purchased_battle_pass_tier_offers":[
				
				],
				"rested_xp_exchange":0,
				"level":0,
				"xp_overflow":0,
				"rested_xp":0,
				"rested_xp_mult":0,
				"accountLevel":0,
				"competitive_identity":{
				
				},
				"inventory_limit_bonus":0,
				"last_applied_loadout":"puma",
				"daily_rewards":{
				
				},
				"xp":0,
				"season_friend_match_boost":0,
				"active_loadout_index":0
			}
		},
		"commandRevision":0
	}
	)"_json;
}